import os
import sys
import subprocess
from datetime import datetime
from pathlib import Path

def initialize():
    pass

    # if (os.path.exists(''))

def clear_screen():
    os.system('cls') if (sys.platform.lower() ==
                         "win32") else os.system('clear')


def colorizeInput(text: str):
    print(text, end='', flush=True)
    return input()


def execute(command: str):
    try:
        kwargs = {
            "shell": True,
            "stdout": subprocess.PIPE,
            "stderr": subprocess.PIPE,
            "text": True
        }

        if (sys.platform.lower() == 'win32'):
            kwargs["creationflags"] = subprocess.CREATE_NO_WINDOW

        result = subprocess.run(command, **kwargs)

        if result.returncode == 0:
            return True
        else:
            return False

    except:
        return False


def escape_newlines_block(text: str):
    text = text.replace("\r\n", "\n")
    core = text.strip("\n")
    escaped = core.replace("\n", r"\n")
    return r"\n" + escaped + r"\n"


def generateINFO():
    info = f'''
#  Generated By Charon DNS Changer v1.1
#  Date    :  {(datetime.now().strftime("%Y-%m-%d %H:%M"))}
#  Author  :  AmirHossein Ghanami (Ch4120N)
#  GitHub  :  GitHub.Com/Ch4120N  
'''
    return escape_newlines_block(info)